Ready to review
danmontielh/Youtube-Clone-Microverse pull request #1
Opened 2019-03-27 18:10 UTC by danmontielh

2019-03-28 07:26 UTC, inhaq requested changes
### Good work on your first project 🏆
I must say you're doing amazing work individually. Here are a few things to fix and improve:

 - Fix your errors by validating it [here](https://validator.w3.org)
 - Improve navbar design by aligning icons properly

Once fixed, kindly resubmit and add me(Inzi) as project reviewer. Happy Coding 😊

2019-03-28 20:56 UTC, danmontielh commented
i have improved mi navbar and i don´t have any error in  Markup Validation Service

2019-03-29 06:35 UTC, inhaq approved these changes
### Great work on your first project 🏆
The design looks good and the code is clean as well. One thing I would like to mention here for your next projects, you don't need to use `div` with CSS selectors. I'll recommend to fix it for this project as well and then submit project completion form. No need to resubmit for review.
###  It's a 👍🏻for this project 🎉

2019-03-29 06:35 UTC, inhaq commented on css/style.css
> +div.header .wrapper {
`div.header` should be `.header` only

2019-03-29 06:35 UTC, inhaq commented on css/style.css
> +div.header .wrapper .logo i {
again here, don't need to use `div` with class names

2019-03-29 16:22 UTC, merged